version: 0.2
phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - yarn install
  build:
    commands:
      - yarn build
      # Use AWS SAM to package the application by using AWS CloudFormation
      # - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
